services:
  database:
    image: postgres:17.5
    restart: unless-stopped
    env_file:
      - .env.database
    ports:
      - 5440:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_ocp:/var/lib/postgresql/datad

volumes:
  postgres_data_ocp:
